-- Find total revenue generated by each product

SELECT p.product_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name;

-- Find top 5 highest revenue products

SELECT p.product_name,
       SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 5;

-- Find customer who placed maximum orders

SELECT c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC
LIMIT 1;

-- Find total orders handled by each store

SELECT s.store_name,
       COUNT(o.order_id) AS total_orders
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
GROUP BY s.store_name;

-- Find best performing store

SELECT s.store_name,
       COUNT(o.order_id) AS total_orders
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
GROUP BY s.store_name
ORDER BY total_orders DESC
LIMIT 1;

-- Find category wise revenue

SELECT c.category_name,
       SUM(p.price * oi.quantity) AS revenue
FROM categories c
JOIN products p
ON c.category_id = p.category_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY c.category_name;

-- Find most sold product

SELECT p.product_name,
       SUM(oi.quantity) AS total_quantity
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 1;

-- Find least sold product

SELECT p.product_name,
       SUM(oi.quantity) AS total_quantity
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity ASC
LIMIT 1;

-- Find total revenue generated by each store

SELECT s.store_name,
       SUM(p.price * oi.quantity) AS revenue
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id
GROUP BY s.store_name;

-- Find top spending customer

SELECT c.customer_name,
       SUM(p.price * oi.quantity) AS amount_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY amount_spent DESC
LIMIT 1;

-- Find average order value

SELECT AVG(order_total) AS average_order_value
FROM
(
    SELECT o.order_id,
           SUM(p.price * oi.quantity) AS order_total
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    JOIN products p
    ON oi.product_id = p.product_id
    GROUP BY o.order_id
) t;

-- Find total revenue of business

SELECT SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id;

-- Find customers from Hyderabad who placed orders

SELECT DISTINCT c.customer_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE c.city='Hyderabad';

-- Find category having highest revenue

SELECT c.category_name,
       SUM(p.price * oi.quantity) AS revenue
FROM categories c
JOIN products p
ON c.category_id = p.category_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY revenue DESC
LIMIT 1;

-- Display complete sales report

SELECT c.customer_name,
       p.product_name,
       oi.quantity,
       p.price,
       (p.price * oi.quantity) AS total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id;